version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  commands:
      - cargo install mdbook mdbook-katex mdbook-toc mdbook-admonish
      - mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html